# BUILD file for web controllers

filegroup(
    name = "controller",
    srcs = glob(["*.java"]),
    visibility = [
        "//main/src/main/java:__pkg__",
    ],
)

# Alias for consistency
filegroup(
    name = "java_sources",
    srcs = glob(["*.java"]),
    visibility = ["//main/src/main/java:__pkg__"],
)