# Buildfarm Admin Deployment
server.port=8080
ui.enable=true

# Valkey Cluster Configuration
valkey.cluster.nodes=
valkey.cluster.enabled=true
valkey.connection.timeout=2000
valkey.connection.pool.max-active=8
valkey.connection.pool.max-idle=8
valkey.connection.pool.min-idle=0
valkey.cluster.username=
valkey.cluster.password=

# SSL/TLS Configuration for ElastiCache
valkey.cluster.ssl.enabled=true
valkey.cluster.ssl.verify-peer=false
valkey.cluster.ssl.start-tls=false
